# -*- coding: utf-8 -*-
"""Traditional Chinese → English term glossary for auto UI translation."""

# Longest keys first when applying replacements.
EN_GLOSSARY: dict[str, str] = {
    "系統清理與優化": "System Cleaner & Optimizer",
    "硬碟健康度檢測": "Disk Health Check",
    "命令列模式": "Command-line mode",
    "彩色日誌控制台": "Color log console",
    "內部使用": "internal use",
    "觸發測試崩潰": "Trigger test crash",
    "啟動後縮至系統匣": "Start minimized to tray",
    "顯示此說明": "Show this help",
    "顯示崩潰報告視窗": "Show crash report window",
    "開啟卸載視窗": "Open uninstall window",
    "正常 GUI 主程式": "Normal GUI application",
    "無參數": "No arguments",
    "記憶體緩衝": "memory buffer",
    "即時 Logger": "Live logger",
    "日誌檔案": "Log file",
    "尚無日誌": "No logs yet",
    "執行日誌": "Runtime log",
    "未選擇路徑": "No path selected",
    "程序執行中": "Process running",
    "仍要繼續清理嗎": "Continue cleaning anyway",
    "建議先關閉以取得最佳清理效果": "Close them first for best results",
    "相關程序仍在執行": "related processes are still running",
    "偵測到": "Detected",
    "卸載完成": "Uninstall complete",
    "無法取得程式路徑": "Cannot get application path",
    "程式檔案將於下次重新開機後刪除": "Program files will be deleted after next reboot",
    "程式資料夾仍保留": "Program folder still remains",
    "可手動刪除": "You may delete it manually",
    "系統清理與優化": "System cleaner & optimizer",
    "存取違規": "Access violation",
    "堆疊溢出": "Stack overflow",
    "未捕獲 C++ 例外": "Uncaught C++ exception",
    "堆積損壞": "Heap corruption",
    "系統或執行期例外": "System or runtime exception",
    "程式已異常結束": "Application crashed",
    "崩潰報告": "Crash report",
    "枚舉目錄": "Enumerating folders",
    "計算大小": "Calculating size",
    "整理結果": "Finalizing results",
    "開始掃描": "Starting scan",
    "已清理": "Cleaned",
    "處理項目": "Processing item",
    "建議關閉": "Recommend off",
    "建議開啟": "Recommend on",
    "遊戲建議": "Gaming tip",
    "省電建議": "Power saver tip",
    "辦公建議": "Office tip",
    "可選調校": "Optional tune",
    "常見可停用": "Often safe to disable",
    "開機啟動": "Run at startup",
    "啟動速度影響": "Boot impact",
    "一般影響": "General impact",
    "開機／效能": "Boot / performance",
    "登錄名稱": "Registry name",
    "最近操作": "Last action",
    "系統效能調校": "System performance tuning",
    "儲存設定": "Storage settings",
    "網路總覽": "Network overview",
    "檢查中": "Checking",
    "無法完成操作": "Operation failed",
    "系統拒絕變更或目前環境不支援": "System denied the change or feature unsupported",
    "需要管理員權限": "Administrator rights required",
    "電源計畫": "Power plan",
    "終極效能": "Ultimate performance",
    "高效能": "High performance",
    "視覺效果": "Visual effects",
    "遊戲模式": "Game Mode",
    "重新讀取": "Reload",
    "重新掃描": "Rescan",
    "掃描完成": "Scan complete",
    "掃描失敗": "Scan failed",
    "掃描中": "Scanning",
    "準備掃描": "Ready to scan",
    "略過": "Skipped",
    "網路磁碟": "network drive",
    "可用記憶體": "Available memory",
    "已整理": "Trimmed",
    "個程序": " processes",
    "工作集": "working set",
    "系統快取": "system cache",
    "清理完成": "Clean complete",
    "清理中": "Cleaning",
    "就緒": "Ready",
    "破壞性": "Destructive",
    "詳細": "Details",
    "開啟資料夾": "Open folder",
    "套用": "Apply",
    "關閉": "Close",
    "取消": "Cancel",
    "確定": "OK",
    "刪除": "Delete",
    "啟用": "Enable",
    "停用": "Disable",
    "已停用": "Disabled",
    "已啟用": "Enabled",
    "執行中": "Running",
    "已停止": "Stopped",
    "未安裝": "Not installed",
    "未知": "Unknown",
    "失敗": "Failed",
    "成功": "Success",
    "完成": "Done",
    "進行中": "In progress",
    "測試中": "Testing",
    "載入中": "Loading",
    "分析中": "Analyzing",
    "最佳化": "Optimize",
    "已最佳化": "Optimized",
    "需要最佳化": "Needs optimization",
    "狀況良好": "Healthy",
    "分析失敗": "Analysis failed",
    "最佳化失敗": "Optimization failed",
    "硬碟": "Disk",
    "磁碟": "Drive",
    "磁碟區": "Volume",
    "容量": "Capacity",
    "介面": "Interface",
    "良好": "Good",
    "注意": "Caution",
    "不良": "Bad",
    "關鍵警告": "Critical warning",
    "無 SMART": "No SMART",
    "無 SMART 資料": "No SMART data",
    "無 SMART 屬性": "No SMART attributes",
    "速度測試": "Speed test",
    "壞軌": "Bad sector",
    "壞軌檢測": "Bad sector check",
    "概況": "Overview",
    "總覽": "Overview",
    "監控": "Monitor",
    "網路測試": "Network test",
    "設定": "Settings",
    "程式": "Processes",
    "啟動項": "Startup",
    "服務": "Services",
    "系統效能": "System performance",
    "儲存": "Storage",
    "網路": "Network",
    "歷史": "History",
    "關於": "About",
    "語言": "Language",
    "管理員": "Administrator",
    "標準使用者": "Standard user",
    "看門狗": "Watchdog",
    "系統匣": "System tray",
    "釋放記憶體": "Free memory",
    "清理": "Clean",
    "掃描": "Scan",
    "優化": "Optimize",
    "優化": "Optimize",
    "系統": "System",
    "使用者": "User",
    "暫存": "Temp",
    "其他": "Other",
    "可用": "Free",
    "已用": "Used",
    "程式": "App",
    "檔案": "File",
    "資料夾": "Folder",
    "空資料夾": "Empty folder",
    "本機磁碟": "Local drive",
    "系統保留": "System reserved",
    "測量中": "Measuring",
    "無法存取": "Access denied",
    "無權限": "No permission",
    "無法讀取": "Cannot read",
    "測量失敗": "Measure failed",
    "子資料夾未測完": "Subfolders incomplete",
    "未測完": "Incomplete",
    "授權": "License",
    "版本": "Version",
    "日誌": "Log",
    "控制台": "Console",
    "管道": "pipe",
    "無效": "Invalid",
    "缺少": "Missing",
    "參數": "parameter",
    "操作": "Action",
    "來源": "Source",
    "用途": "Purpose",
    "狀態": "Status",
    "路徑": "Path",
    "產品": "Product",
    "發行者": "Publisher",
    "備註": "Note",
    "說明": "Description",
    "提示": "Hint",
    "警告": "Warning",
    "錯誤": "Error",
    "確認": "Confirm",
    "返回": "Back",
    "繼續": "Continue",
    "暫停": "Pause",
    "停止": "Stop",
    "開始": "Start",
    "重新": "Re-",
    "自動": "Auto",
    "手動": "Manual",
    "自訂": "Custom",
    "目前": "Current",
    "最快": "Fastest",
    "平均": "Average",
    "解析": "Resolve",
    "逾時": "Timeout",
    "路由器": "Router",
    "下載": "Download",
    "上傳": "Upload",
    "延遲": "Latency",
    "上網": "Internet",
    "連線": "Connection",
    "介面卡": "Adapter",
    "代理": "Proxy",
    "封包": "Packet",
    "遺失率": "Loss rate",
    "訊號": "Signal",
    "未連線": "Not connected",
    "玩家": "Gaming",
    "開發者": "Developer",
    "一般": "General",
    "進階": "Advanced",
    "安全": "Safe",
    "平衡": "Balanced",
    "省電": "Power saver",
    "休眠": "Hibernate",
    "開機": "Boot",
    "啟動": "Startup",
    "遊戲": "Game",
    "效能": "Performance",
    "記憶體": "Memory",
    "處理器": "Processor",
    "顯示卡": "GPU",
    "溫度": "Temperature",
    "風扇": "Fan",
    "轉速": "RPM",
    "健康": "Health",
    "屬性": "Attributes",
    "報告": "Report",
    "診斷": "Diagnostics",
    "工具": "Tools",
    "測速": "Speed test",
    "抽樣": "Sampling",
    "讀取": "Read",
    "寫入": "Write",
    "僅讀取": "Read only",
    "讀+寫": "Read + write",
    "暫存檔": "temp file",
    "樣本": "sample",
    "建議": "Recommended",
    "已分析": "Analyzed",
    "已最佳化": "Optimized",
    "已清理": "Cleaned",
    "已停止": "Stopped",
    "已啟用": "Enabled",
    "已停用": "Disabled",
    "已掃描": "Scanned",
    "分析": "Analyze",
    "回收筒": "Recycle Bin",
    "枚舉目錄": "Enumerating folders",
    "計算大小": "Calculating size",
    "整理結果": "Finalizing results",
    "開始掃描": "Starting scan",
    "執行日誌": "Runtime log",
    "重新整理": "Refresh",
    "解除安裝": "Uninstall",
    "快速預設": "Quick presets",
    "清理歷史": "Clean history",
    "文件地圖": "File map",
    "文件占比": "File share",
    "副檔名": "Extension",
    "檔案樹": "File tree",
    "內容": "Content",
    "名稱": "Name",
    "類型": "Type",
    "大小": "Size",
    "標籤": "Tag",
    "破壞性": "Destructive",
    "就緒": "Ready",
    "處理中": "Processing",
    "處理項目": "Processing item",
    "本次釋放": "Freed this run",
    "本次已釋放": "Freed this run",
    "剩餘可清理": "Remaining reclaimable",
    "預計清理": "Estimated cleanup",
    "掃描後顯示": "Show after scan",
    "開啟資料夾": "Open folder",
    "系統優化": "System optimization",
    "系統優化概覽": "System optimization overview",
    "關鍵指標": "Key metrics",
    "快速操作": "Quick actions",
    "系統狀態": "System status",
    "一鍵預設方案": "One-click presets",
    "套用優化預設": "Apply optimization preset",
    "只顯示常見可停用": "Show commonly disableable only",
    "遊戲調校": "Gaming tune",
    "一鍵遊戲調校": "Quick gaming tune",
    "電源計畫": "Power plan",
    "快速啟動": "Fast startup",
    "遊戲列": "Game bar",
    "傳遞優化": "Delivery optimization",
    "網路節流": "Network throttling",
    "處理器排程": "Processor scheduling",
    "硬體加速": "Hardware acceleration",
    "磁碟最佳化": "Drive optimization",
    "磁碟分析": "Drive analysis",
    "儲存感知": "Storage Sense",
    "暫存檔案": "Temporary files",
    "資源回收筒": "Recycle Bin",
    "休眠檔案": "Hibernation file",
    "系統還原": "System Restore",
    "還原點": "Restore point",
    "無法完成操作": "Could not complete",
    "無法建立圖形裝置": "Could not create graphics device",
    "程式已異常結束": "Application crashed",
    "請複製下方報告": "Copy the report below",
    "重新啟動": "Restart",
    "複製": "Copy",
    "堆疊追蹤": "Stack trace",
    "日誌尾端": "Log tail",
    "原始 JSON": "Raw JSON",
    "例外代碼": "Exception code",
    "行程 ID": "Process ID",
    "執行緒 ID": "Thread ID",
    "模組": "Module",
    "位址": "Address",
    "時間": "Time",
    "報告檔": "Report file",
    "來源": "Source",
}
